-- Terminology seed data for Supabase

INSERT INTO public.terminology (term_key, locale, title, description, sort_order) VALUES
  ('reps', 'en', 'Reps', 'Number of times you perform an exercise consecutively.', 1),
  ('set', 'en', 'Set', 'A group of repetitions. For example: 3 sets of 10 reps means 30 repetitions total divided into 3 groups.', 2),
  ('rt', 'en', 'RT', 'Total Repetitions: perform all the reps with your preferred sets, reps, and tempo (if not specified).', 3),
  ('amrap', 'en', 'AMRAP', 'As Many Reps As Possible: perform as many reps as you can in a given time.', 4),
  ('emom', 'en', 'EMOM', 'Every Minute on the Minute: start a set every minute. Rest during the remaining time.', 5),
  ('ramping', 'en', 'Ramping', 'Method where the load increases with each set.', 6),
  ('mav', 'en', 'MAV', 'Massima Alzata Veloce: perform as many reps as possible with a load while keeping control and good speed.', 7),
  ('isokinetic', 'en', 'Isokinetic', 'Exercises performed at a constant speed.', 8),
  ('tut', 'en', 'TUT', 'Indicates how long a repetition should last. You can manage the duration of each phase.', 9),
  ('iso', 'en', 'ISO', 'Indicates a pause at a specific point of the repetition.', 10),
  ('som', 'en', 'SOM', 'Indicates the duration of each phase of the repetition.', 11),
  ('deload', 'en', 'Deload', 'Last week of the program to prepare for max attempts.', 12),
  ('reps', 'it', 'Reps (Ripetizioni)', 'Numero di volte che esegui un esercizio consecutivamente.', 1),
  ('set', 'it', 'Set (Serie)', 'Un gruppo di ripetizioni. Es: 3 serie da 10 reps significa 30 ripetizioni totali, divise in 3 gruppi.', 2),
  ('rt', 'it', 'RT', 'Ripetizioni Totali: indica che devi fare tutte quelle reps, con libera scelta di serie, ripetizioni e tempo (se non indicato).', 3),
  ('amrap', 'it', 'AMRAP', 'As Many Reps As Possible: esegui quante più ripetizioni possibili in un tempo determinato.', 4),
  ('emom', 'it', 'EMOM', 'Every Minute On Minute: inizi un set ogni minuto. Il tempo restante serve per riposare.', 5),
  ('ramping', 'it', 'Ramping', 'Metodo che prevede un incremento del peso ad ogni serie', 6),
  ('mav', 'it', 'MAV', 'Massima Alzata Veloce: si riferisce a una metodologia in cui si cerca di eseguire il maggior numero di ripetizioni possibili con un carico, mantenendo sempre il controllo del movimento e una buona velocità di esecuzione.', 7),
  ('isokinetic', 'it', 'Isocinetici', 'Esercizi svolti a velocità costante.', 8),
  ('tut', 'it', 'TUT', 'Indica quanto deve durare una ripetizione. Puoi gestire tu la durata di ogni fase della rep.', 9),
  ('iso', 'it', 'ISO', 'Indica il fermo a un punto specifico dell''esecuzione della rep', 10),
  ('som', 'it', 'SOM', 'Indica la durata di ogni fase della ripetizione.', 11),
  ('deload', 'it', 'Scarico', 'Ultima settimana della scheda per prepararsi ai massimali.', 12),
  ('reps', 'es', 'Reps (Repeticiones)', 'Número de veces que realizas un ejercicio de forma consecutiva.', 1),
  ('set', 'es', 'Set (Series)', 'Un grupo de repeticiones. Por ejemplo: 3 series de 10 reps son 30 repeticiones en total divididas en 3 grupos.', 2),
  ('rt', 'es', 'RT', 'Repeticiones Totales: realiza todas las reps con las series, repeticiones y tempo que prefieras (si no se indica).', 3),
  ('amrap', 'es', 'AMRAP', 'As Many Reps As Possible: haz tantas repeticiones como puedas en un tiempo determinado.', 4),
  ('emom', 'es', 'EMOM', 'Every Minute on the Minute: comienza una serie cada minuto. Descansa el tiempo restante.', 5),
  ('ramping', 'es', 'Ramping', 'Método en el que la carga aumenta en cada serie.', 6),
  ('mav', 'es', 'MAV', 'Massima Alzata Veloce: realiza el mayor número de repeticiones posible con una carga manteniendo el control y una buena velocidad de ejecución.', 7),
  ('isokinetic', 'es', 'Isocinéticos', 'Ejercicios realizados a velocidad constante.', 8),
  ('tut', 'es', 'TUT', 'Indica cuánto debe durar una repetición. Puedes gestionar la duración de cada fase.', 9),
  ('iso', 'es', 'ISO', 'Indica la pausa en un punto específico de la repetición.', 10),
  ('som', 'es', 'SOM', 'Indica la duración de cada fase de la repetición.', 11),
  ('deload', 'es', 'Descarga', 'Última semana del programa para prepararse para los máximos.', 12);
