# .github/workflows/secret-scan.yml
name: Secret Scan
on:
  push: { branches: ["**"] }
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # fetch full history so TH can compute ranges if needed
          fetch-depth: 0
      - uses: trufflesecurity/trufflehog@v3.90.6
        with:
          scanArguments: >-
            --json --only-verified=false --fail --since-history 10y .

  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: gitleaks/gitleaks-action@v2
        with:
          version: latest
          args: detect --report-format sarif --report-path gitleaks.sarif --redact --no-banner
      - uses: github/codeql-action/upload-sarif@v3
        if: always()
        with: { sarif_file: gitleaks.sarif }